// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package media

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockVLCAudioService creates a new instance of MockVLCAudioService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVLCAudioService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVLCAudioService {
	mock := &MockVLCAudioService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVLCAudioService is an autogenerated mock type for the VLCAudioService type
type MockVLCAudioService struct {
	mock.Mock
}

type MockVLCAudioService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVLCAudioService) EXPECT() *MockVLCAudioService_Expecter {
	return &MockVLCAudioService_Expecter{mock: &_m.Mock}
}

// CheckForPlayer provides a mock function for the type MockVLCAudioService
func (_mock *MockVLCAudioService) CheckForPlayer() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CheckForPlayer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVLCAudioService_CheckForPlayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckForPlayer'
type MockVLCAudioService_CheckForPlayer_Call struct {
	*mock.Call
}

// CheckForPlayer is a helper method to define mock.On call
func (_e *MockVLCAudioService_Expecter) CheckForPlayer() *MockVLCAudioService_CheckForPlayer_Call {
	return &MockVLCAudioService_CheckForPlayer_Call{Call: _e.mock.On("CheckForPlayer")}
}

func (_c *MockVLCAudioService_CheckForPlayer_Call) Run(run func()) *MockVLCAudioService_CheckForPlayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVLCAudioService_CheckForPlayer_Call) Return(err error) *MockVLCAudioService_CheckForPlayer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVLCAudioService_CheckForPlayer_Call) RunAndReturn(run func() error) *MockVLCAudioService_CheckForPlayer_Call {
	_c.Call.Return(run)
	return _c
}

// GetAlsaDeviceName provides a mock function for the type MockVLCAudioService
func (_mock *MockVLCAudioService) GetAlsaDeviceName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAlsaDeviceName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockVLCAudioService_GetAlsaDeviceName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAlsaDeviceName'
type MockVLCAudioService_GetAlsaDeviceName_Call struct {
	*mock.Call
}

// GetAlsaDeviceName is a helper method to define mock.On call
func (_e *MockVLCAudioService_Expecter) GetAlsaDeviceName() *MockVLCAudioService_GetAlsaDeviceName_Call {
	return &MockVLCAudioService_GetAlsaDeviceName_Call{Call: _e.mock.On("GetAlsaDeviceName")}
}

func (_c *MockVLCAudioService_GetAlsaDeviceName_Call) Run(run func()) *MockVLCAudioService_GetAlsaDeviceName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVLCAudioService_GetAlsaDeviceName_Call) Return(s string) *MockVLCAudioService_GetAlsaDeviceName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockVLCAudioService_GetAlsaDeviceName_Call) RunAndReturn(run func() string) *MockVLCAudioService_GetAlsaDeviceName_Call {
	_c.Call.Return(run)
	return _c
}

// PlayAudio provides a mock function for the type MockVLCAudioService
func (_mock *MockVLCAudioService) PlayAudio(ctx context.Context, loop bool, audioPathOrUrl string) error {
	ret := _mock.Called(ctx, loop, audioPathOrUrl)

	if len(ret) == 0 {
		panic("no return value specified for PlayAudio")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool, string) error); ok {
		r0 = returnFunc(ctx, loop, audioPathOrUrl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVLCAudioService_PlayAudio_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PlayAudio'
type MockVLCAudioService_PlayAudio_Call struct {
	*mock.Call
}

// PlayAudio is a helper method to define mock.On call
//   - ctx
//   - loop
//   - audioPathOrUrl
func (_e *MockVLCAudioService_Expecter) PlayAudio(ctx interface{}, loop interface{}, audioPathOrUrl interface{}) *MockVLCAudioService_PlayAudio_Call {
	return &MockVLCAudioService_PlayAudio_Call{Call: _e.mock.On("PlayAudio", ctx, loop, audioPathOrUrl)}
}

func (_c *MockVLCAudioService_PlayAudio_Call) Run(run func(ctx context.Context, loop bool, audioPathOrUrl string)) *MockVLCAudioService_PlayAudio_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bool), args[2].(string))
	})
	return _c
}

func (_c *MockVLCAudioService_PlayAudio_Call) Return(err error) *MockVLCAudioService_PlayAudio_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVLCAudioService_PlayAudio_Call) RunAndReturn(run func(ctx context.Context, loop bool, audioPathOrUrl string) error) *MockVLCAudioService_PlayAudio_Call {
	_c.Call.Return(run)
	return _c
}

// SetAlsaDevice provides a mock function for the type MockVLCAudioService
func (_mock *MockVLCAudioService) SetAlsaDevice(alsaDeviceName string) {
	_mock.Called(alsaDeviceName)
	return
}

// MockVLCAudioService_SetAlsaDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAlsaDevice'
type MockVLCAudioService_SetAlsaDevice_Call struct {
	*mock.Call
}

// SetAlsaDevice is a helper method to define mock.On call
//   - alsaDeviceName
func (_e *MockVLCAudioService_Expecter) SetAlsaDevice(alsaDeviceName interface{}) *MockVLCAudioService_SetAlsaDevice_Call {
	return &MockVLCAudioService_SetAlsaDevice_Call{Call: _e.mock.On("SetAlsaDevice", alsaDeviceName)}
}

func (_c *MockVLCAudioService_SetAlsaDevice_Call) Run(run func(alsaDeviceName string)) *MockVLCAudioService_SetAlsaDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockVLCAudioService_SetAlsaDevice_Call) Return() *MockVLCAudioService_SetAlsaDevice_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockVLCAudioService_SetAlsaDevice_Call) RunAndReturn(run func(alsaDeviceName string)) *MockVLCAudioService_SetAlsaDevice_Call {
	_c.Run(run)
	return _c
}
