all: false
dir: '{{.InterfaceDir}}'
filename: mock_{{.InterfaceName | snakecase}}.go
force-file-write: true
formatter: goimports
log-level: info
structname: '{{.Mock}}{{.InterfaceName}}'
pkgname: '{{.SrcPackageName}}'
recursive: true
require-template-schema-exists: true
template: testify
template-schema: '{{.Template}}.schema.json'
packages:
  github.com/danesparza/fxaudio:
    config:
      all: true

# To generate mocks: docker run -v "$PWD":/src -w /src vektra/mockery:3